# Generated by Django 4.2.7 on 2025-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_folder_uploadedfile_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='invite_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='group_media/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='media_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='group_media/thumbnails/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
